name: Laravel with php 8.0

on:
  pull_request

jobs:
  laravel-php-81:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:10.3
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: customerapp_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - uses: actions/checkout@v1

    - uses: jitterbit/get-changed-files@v1

    - name: Copy .env
      run: |
        php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Cache Dependencies
      uses: actions/cache@v2
      env:
        cache-name: cache-composer
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.composer
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --prefer-dist

    - name: Update Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Generate key
      run: php artisan key:generate

    - name: Optimize Laravel
      run: |
        php artisan optimize:clear
        php artisan view:clear
        php artisan optimize
        php artisan view:cache

    - name: Clear Config
      run: |
        php artisan config:clear
        php artisan route:clear

    - name: Run PHPCS
      run: |
        ./vendor/bin/pint --test

    - name: Executing tests (Unit and Feature tests)
      run: ./vendor/bin/phpunit

    - uses: colpal/actions-clean@v1
      if: ${{ always() }}
