name: Laravel with php 8.0

on:
  pull_request

jobs:
  laravel-php-81:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:10.3
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    env:
      DB_DATABASE: app
      DB_USERNAME: root
      DB_PASSWORD: password

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - uses: actions/checkout@v1

    - uses: jitterbit/get-changed-files@v1
    
    - name: Copy .env
      run: |
        php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Cache Dependencies
      uses: actions/cache@v3.0.7
      env:
        cache-name: cache-composer
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.composer
        key: ${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}

    - name: Install Dependencies
      run: composer install --no-interaction

    - name: Update Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Generate key
      run: php artisan key:generate

    - name: Optimize Laravel
      run: |
        php artisan optimize:clear
        php artisan view:clear
        php artisan optimize
        php artisan view:cache

    - name: Clear Config
      run: |
        php artisan config:clear
        php artisan route:clear

    - name: Run PINT
      run: ./vendor/bin/pint --test

    - name: Executing tests (Unit and Feature tests)
      run: ./vendor/bin/phpunit
